### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by brnicot** [knojector/SteamAuthenticationBundle#4]
Hi,

New to Symfony, I tried to install your bundle and followed all your instructions but can't get it to work.
When I click on the button to login, I'm just redirected to https://steamcommunity.com/
If you have an idea ?

Sorry if it's my fault as I said I'm new to Symfony.
Thanks

**Comment by knojector** [comment]
Hi,

did you followed the instructions for installation? I encountered this kind of problems during development because of a wrong configuration of the bundle's yml file.

**Comment by brnicot** [comment]
yes as I said I followed everything you said to do on your page, even if I struggled due to package versions. the problem is that I don't even know where to look :/

**Comment by knojector** [comment]
Could you post the content of the `knojector_steam_authentication.yml` file in the `config/packages` directory?

**Comment by brnicot** [comment]
sure, here it is
`# https://github.com/knojector/SteamAuthenticationBundle for configuration documentation
knojector_steam_authentication:
    api_key: "%env(STEAM_API_KEY)%"
    login_route: 'index'
    login_redirect: 'index'
    user_class: 'User'
`

thanks :)

**Comment by knojector** [comment]
Could you choose two different routes for login_route and login_redirect?
Btw. You need to enter to full qualified Classname e.q `App\Entity\User`. Is `User` your correct namespace?

**Comment by brnicot** [comment]
can't get it to work even with that, could you please provide a working sample app ?

**Comment by Gasjki** [comment]
Hi @brnicot,

I'll open an issue about your error because I know how to solve it. Until then, please open next files and do as I say 😀 
1. Security -> Firewall -> SteamListener
> Overwrite line no. 78 with this:
$claimedId = str_replace('https://steamcommunity.com/openid/id/', '', ,$request->query->get('openid_claimed_id'));

2. Http -> SteamApiClient
> Overwrite constant from line no.13 with this:
const STEAM_API = 'https://api.steampowered.com';

3. Resources -> views -> login.html.twig
> Overwrite line no.1 and no. 8:

<form method="post" action="https://steamcommunity.com/openid/login">
.....
<button type="submit"><img src="https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_01.png" /></button>

As you can see all you needed to do was to update HTTP to HTTPS. Why? Read this article about it: [https://www.reddit.com/r/Steam/comments/8a7gsu/steam_openid_broken_for_many_websites_fix_inside/](Reddit)


@knojector can you update project as well ? 😃

**Comment by brnicot** [comment]
Hello :)
Nice that they switched to https but would have been better if they had announced it somewhere.. I'll try your fix tonight, thanks !

**Comment by Gasjki** [comment]
@brnicot I know, but that's how Valve works, right ?:))

**Comment by knojector** [comment]
Thank you @Gasjki for investigating. 

I'm sorry, I was very busy the last weeks. I updated the bundle to 1.0.7 with a fix for the http issue.

**Comment by Gasjki** [comment]
@knojector You forgot to change form action to httpS . 😆

**Comment by knojector** [comment]
:man_facepalming:
